"""(change): vertical owner to digital head

Revision ID: 05500b50b9ff
Revises:
Create Date: 2026-03-30 23:23:49.837869

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "05500b50b9ff"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "digital_head_map",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("vertical_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], onupdate="cascade", ondelete="cascade"
        ),
        sa.ForeignKeyConstraint(
            ["vertical_id"], ["verticals.id"], onupdate="cascade", ondelete="cascade"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vertical_id", "user_id", name="uq_vertical_user"),
    )
    # op.drop_index(op.f('uq_vertical_user'), table_name='vertical_owner_map')
    op.drop_table("vertical_owner_map")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vertical_owner_map",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("vertical_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.Column(
            "is_active",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("vertical_owner_map_ibfk_1"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vertical_id"],
            ["verticals.id"],
            name=op.f("vertical_owner_map_ibfk_2"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("uq_vertical_user"),
        "vertical_owner_map",
        ["vertical_id", "user_id"],
        unique=True,
    )
    op.drop_table("digital_head_map")
    # ### end Alembic commands ###
