"""using app_id and dept_id seperately in app_dept_questions

Revision ID: 09ff121a4a74
Revises: a9340d420e38
Create Date: 2026-02-03 18:40:13.314931

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "09ff121a4a74"
down_revision: Union[str, Sequence[str], None] = "a9340d420e38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add new columns first
    op.add_column(
        "app_dept_questions",
        sa.Column("application_id", sa.String(length=40), nullable=False),
    )
    op.add_column(
        "app_dept_questions",
        sa.Column("department_id", sa.Integer(), nullable=False),
    )

    # 2. DROP FOREIGN KEYS that depend on app_dept_id
    op.drop_constraint(
        op.f("app_dept_questions_ibfk_1"),
        "app_dept_questions",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("app_dept_questions_ibfk_2"),
        "app_dept_questions",
        type_="foreignkey",
    )

    # 3. NOW it’s safe to drop the index
    op.drop_index(
        op.f("app_dept_id"),
        table_name="app_dept_questions",
    )

    # 4. Create new constraints
    op.create_unique_constraint(
        None,
        "app_dept_questions",
        ["application_id", "department_id", "question_id"],
    )

    op.create_foreign_key(
        None,
        "app_dept_questions",
        "questions",
        ["question_id"],
        ["id"],
        ondelete="cascade",
    )

    op.create_foreign_key(
        None,
        "app_dept_questions",
        "application_departments",
        ["application_id", "department_id"],
        ["application_id", "department_id"],
        ondelete="cascade",
    )

    # 5. Finally drop the old column
    op.drop_column("app_dept_questions", "app_dept_id")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_dept_questions",
        sa.Column("app_dept_id", mysql.VARCHAR(length=40), nullable=False),
    )
    op.drop_constraint(None, "app_dept_questions", type_="foreignkey")
    op.drop_constraint(None, "app_dept_questions", type_="foreignkey")
    op.create_foreign_key(
        op.f("app_dept_questions_ibfk_1"),
        "app_dept_questions",
        "application_departments",
        ["app_dept_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("app_dept_questions_ibfk_2"),
        "app_dept_questions",
        "questions",
        ["question_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "app_dept_questions", type_="unique")
    op.create_index(
        op.f("app_dept_id"),
        "app_dept_questions",
        ["app_dept_id", "question_id"],
        unique=True,
    )
    op.drop_column("app_dept_questions", "department_id")
    op.drop_column("app_dept_questions", "application_id")
    # ### end Alembic commands ###
