"""(fix): app questions set id as foriegn key in app questions

Revision ID: 1112d1228d94
Revises: cabf34056c62
Create Date: 2026-02-09 09:20:17.305241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1112d1228d94'
down_revision: Union[str, Sequence[str], None] = 'cabf34056c62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('application_questions_ibfk_1'), 'application_questions', type_='foreignkey')
    op.create_foreign_key(None, 'application_questions', 'question_sets', ['question_set_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application_questions', type_='foreignkey')
    op.create_foreign_key(op.f('application_questions_ibfk_1'), 'application_questions', 'questions', ['question_set_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
