"""(add): adding access token hash to user session

Revision ID: 119c1c2da610
Revises: 6322f7683f4f
Create Date: 2026-04-05 14:55:02.940253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '119c1c2da610'
down_revision: Union[str, Sequence[str], None] = '6322f7683f4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('access_token_hash', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'access_token_hash')
    # ### end Alembic commands ###
