"""(add_on):deparment quessionnaire real thi time

Revision ID: 1abfe1ee91b2
Revises: 2102ccf7b5d8
Create Date: 2026-02-03 15:21:35.399769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1abfe1ee91b2'
down_revision: Union[str, Sequence[str], None] = '2102ccf7b5d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_dept_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_dept_id', sa.String(length=40), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['app_dept_id'], ['application_departments.id'], onupdate='cascade', ondelete='cascade'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_dept_id', 'question_id')
    )
    op.create_table('app_dept_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_dept_question_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.String(length=1000), nullable=True),
    sa.Column('author_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['app_dept_question_id'], ['app_dept_questions.id'], onupdate='cascade', ondelete='cascade'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], onupdate='cascade', ondelete='set null'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_dept_question_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_dept_answers')
    op.drop_table('app_dept_questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
