"""(add_on):deparment quessionnaire

Revision ID: 2102ccf7b5d8
Revises: 9b6ab3553704
Create Date: 2026-02-03 15:17:15.850833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2102ccf7b5d8'
down_revision: Union[str, Sequence[str], None] = '9b6ab3553704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
