"""app criticality hgh medium split

Revision ID: 2538702bd11d
Revises: 1112d1228d94
Create Date: 2026-02-09 14:23:57.282360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2538702bd11d'
down_revision: Union[str, Sequence[str], None] = '1112d1228d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_answers', 'answer_text',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.add_column('application_questions', sa.Column('is_high', sa.Boolean(), nullable=False))
    op.add_column('application_questions', sa.Column('is_medium', sa.Boolean(), nullable=False))
    op.drop_column('application_questions', 'weight')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_questions', sa.Column('weight', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('application_questions', 'is_medium')
    op.drop_column('application_questions', 'is_high')
    op.alter_column('application_answers', 'answer_text',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###
