"""(add):app type and is ai

Revision ID: 2a9b6398ea52
Revises: 6b64cbd08909
Create Date: 2026-02-11 11:20:32.074695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a9b6398ea52'
down_revision: Union[str, Sequence[str], None] = '6b64cbd08909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('app_type', sa.String(length=100), nullable=True))
    op.add_column('applications', sa.Column('is_app_ai', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'is_app_ai')
    op.drop_column('applications', 'app_type')
    # ### end Alembic commands ###
