"""new

Revision ID: 310174b859bb
Revises: f07ffd311ec4
Create Date: 2026-03-25 22:58:07.876641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '310174b859bb'
down_revision: Union[str, Sequence[str], None] = 'f07ffd311ec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_departments', sa.Column('go_live_at', sa.DateTime(), nullable=True))
    op.add_column('applications', sa.Column('vertical_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'applications', 'verticals', ['vertical_id'], ['id'], onupdate='cascade', ondelete='set null')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'vertical_id')
    op.drop_column('application_departments', 'go_live_at')
    # ### end Alembic commands ###
