"""app questionnaire for priority classififcations and dept sub categories

Revision ID: 334b4b84b3ca
Revises: 09ff121a4a74
Create Date: 2026-02-09 09:03:56.582519

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "334b4b84b3ca"
down_revision: Union[str, Sequence[str], None] = "09ff121a4a74"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question_sets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "application_questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_set_id", sa.Integer(), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_set_id"], ["questions.id"], ondelete="cascade"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "application_answers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("app_question_id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.String(length=40), nullable=False),
        sa.Column("answer_text", sa.String(length=1000), nullable=True),
        sa.Column("author_id", sa.String(length=40), nullable=True),
        sa.ForeignKeyConstraint(
            ["app_question_id"],
            ["application_questions.id"],
            onupdate="cascade",
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            onupdate="cascade",
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], onupdate="cascade", ondelete="set null"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("application_id", "app_question_id"),
    )
    op.add_column(
        "application_departments",
        sa.Column("app_category", sa.String(length=40), nullable=True),
    )
    op.add_column(
        "application_departments",
        sa.Column("category_status", sa.String(length=40), nullable=True),
    )
    op.add_column(
        "applications", sa.Column("question_set_id", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "applications", type_="foreignkey")
    op.drop_column("applications", "question_set_id")
    op.drop_column("application_departments", "category_status")
    op.drop_column("application_departments", "app_category")
    op.drop_table("application_answers")
    op.drop_table("application_questions")
    op.drop_table("question_sets")
    # ### end Alembic commands ###
