"""(add): added verticals and reoved uniquness on user fullname

Revision ID: 520bc6635815
Revises: 
Create Date: 2026-03-25 19:53:49.970026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '520bc6635815'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verticals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=70), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vertical_owner_map',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vertical_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='cascade', ondelete='cascade'),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('assessment_cycles')
    op.drop_table('audit_entries')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.create_index('ix_users_full_name', 'users', ['full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_full_name', table_name='users')
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=True)
    op.create_table('audit_entries',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('application_id', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('change_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('old_value', mysql.TEXT(), nullable=True),
    sa.Column('new_value', mysql.TEXT(), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('user_email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('reason', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('audit_entries_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('audit_entries_ibfk_2'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('assessment_cycles',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('application_id', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('cycle_number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fiscal_year', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('start_date', mysql.DATETIME(), nullable=False),
    sa.Column('end_date', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('assessment_cycles_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('vertical_owner_map')
    op.drop_table('verticals')
    # ### end Alembic commands ###
