"""evidence changes

Revision ID: 5a72d175b3e9
Revises: 
Create Date: 2026-01-02 10:47:51.456459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a72d175b3e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_evidences', sa.Column('uploader_id', sa.String(length=40), nullable=False))
    op.add_column('application_evidences', sa.Column('sevirity', sa.String(length=20), nullable=False))
    op.add_column('application_evidences', sa.Column('comment', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'application_evidences', 'users', ['uploader_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application_evidences', type_='foreignkey')
    op.drop_column('application_evidences', 'comment')
    op.drop_column('application_evidences', 'sevirity')
    op.drop_column('application_evidences', 'uploader_id')
    # ### end Alembic commands ###
