"""(add_on):sequnece adjustment for questions

Revision ID: 635aab99b3c6
Revises: 1abfe1ee91b2
Create Date: 2026-02-03 15:24:36.972713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '635aab99b3c6'
down_revision: Union[str, Sequence[str], None] = '1abfe1ee91b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_dept_questions', sa.Column('sequence_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_dept_questions', 'sequence_number')
    # ### end Alembic commands ###
