"""(fix):changed dept question to template question link model

Revision ID: 6b64cbd08909
Revises: 2538702bd11d
Create Date: 2026-02-10 10:20:35.201975

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "6b64cbd08909"
down_revision: Union[str, Sequence[str], None] = "2538702bd11d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dept_question_sets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], ondelete="cascade"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("department_id"),
    )
    op.create_table(
        "dept_questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_set_id", sa.Integer(), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("is_mandatory", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_set_id"], ["dept_question_sets.id"], ondelete="cascade"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # 🔥 MySQL requires FKs to be dropped before indexes / tables

    op.drop_constraint(
        "app_dept_questions_ibfk_2",
        "app_dept_questions",
        type_="foreignkey",
    )

    op.drop_constraint(
        "app_dept_questions_ibfk_1",
        "app_dept_questions",
        type_="foreignkey",
    )
    ##

    op.drop_table("questions")
    op.add_column(
        "app_dept_answers",
        sa.Column("application_id", sa.String(length=40), nullable=False),
    )
    op.add_column(
        "app_dept_answers", sa.Column("department_id", sa.Integer(), nullable=False)
    )
    op.add_column(
        "app_dept_answers", sa.Column("dept_question_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint(
        op.f("app_dept_answers_ibfk_1"), "app_dept_answers", type_="foreignkey"
    )
    op.drop_index(op.f("app_dept_question_id"), table_name="app_dept_answers")
    op.drop_column("app_dept_answers", "app_dept_question_id")
    op.drop_table("app_dept_questions")

    op.create_unique_constraint(
        "uix_app_dept_question_answer",
        "app_dept_answers",
        ["application_id", "department_id", "dept_question_id"],
    )

    op.drop_constraint(
        op.f("app_dept_answers_ibfk_2"), "app_dept_answers", type_="foreignkey"
    )

    op.create_foreign_key(
        None,
        "app_dept_answers",
        "departments",
        ["department_id"],
        ["id"],
        ondelete="cascade",
    )
    op.create_foreign_key(
        None,
        "app_dept_answers",
        "applications",
        ["application_id"],
        ["id"],
        ondelete="cascade",
    )
    op.create_foreign_key(
        None, "app_dept_answers", "users", ["author_id"], ["id"], ondelete="set null"
    )
    op.create_foreign_key(
        None,
        "app_dept_answers",
        "dept_questions",
        ["dept_question_id"],
        ["id"],
        ondelete="cascade",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_dept_answers",
        sa.Column(
            "app_dept_question_id", mysql.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "app_dept_answers", type_="foreignkey")
    op.drop_constraint(None, "app_dept_answers", type_="foreignkey")
    op.drop_constraint(None, "app_dept_answers", type_="foreignkey")
    op.drop_constraint(None, "app_dept_answers", type_="foreignkey")
    op.create_foreign_key(
        op.f("app_dept_answers_ibfk_2"),
        "app_dept_answers",
        "users",
        ["author_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("app_dept_answers_ibfk_1"),
        "app_dept_answers",
        "app_dept_questions",
        ["app_dept_question_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "uix_app_dept_question_answer", "app_dept_answers", type_="unique"
    )
    op.create_index(
        op.f("app_dept_question_id"),
        "app_dept_answers",
        ["app_dept_question_id"],
        unique=True,
    )
    op.drop_column("app_dept_answers", "dept_question_id")
    op.drop_column("app_dept_answers", "department_id")
    op.drop_column("app_dept_answers", "application_id")
    op.create_table(
        "questions",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("text", mysql.TEXT(), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.Column(
            "is_active",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "app_dept_questions",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("question_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column(
            "sequence_number", mysql.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "is_default",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("application_id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column(
            "department_id", mysql.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["application_id", "department_id"],
            [
                "application_departments.application_id",
                "application_departments.department_id",
            ],
            name=op.f("app_dept_questions_ibfk_2"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("app_dept_questions_ibfk_1"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("application_id"),
        "app_dept_questions",
        ["application_id", "department_id", "question_id"],
        unique=True,
    )
    op.drop_table("dept_questions")
    op.drop_table("dept_question_sets")
    # ### end Alembic commands ###
