"""default priority medium for apps

Revision ID: 7f8a9e973543
Revises: c6601c98c545
Create Date: 2026-01-21 09:08:52.633457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7f8a9e973543'
down_revision: Union[str, Sequence[str], None] = 'c6601c98c545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'app_priority',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'app_priority',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
