"""(add): adding severity to categorize crown jewel

Revision ID: 91025ba63adb
Revises: fad375d21a43
Create Date: 2026-03-05 19:28:27.761219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91025ba63adb'
down_revision: Union[str, Sequence[str], None] = 'fad375d21a43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('severity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'severity')
    # ### end Alembic commands ###
