"""(fix): using standarddized controls and status per department

Revision ID: 9944d7d9acee
Revises: 91025ba63adb
Create Date: 2026-03-08 00:21:15.446361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9944d7d9acee'
down_revision: Union[str, Sequence[str], None] = '91025ba63adb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_controls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=52), nullable=False),
    sa.Column('control_type', sa.String(length=52), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_control_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.String(length=40), nullable=False),
    sa.Column('department_control_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=52), nullable=False),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['department_control_id'], ['department_controls.id'], onupdate='cascade', ondelete='cascade'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('application_departments', sa.Column('ended_at', sa.DateTime(), nullable=True))
    op.add_column('application_departments', sa.Column('updated_by', sa.String(length=40), nullable=True))
    op.alter_column('application_departments', 'started_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_foreign_key(None, 'application_departments', 'users', ['updated_by'], ['id'], onupdate='cascade', ondelete='set null')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application_departments', type_='foreignkey')
    op.alter_column('application_departments', 'started_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('application_departments', 'updated_by')
    op.drop_column('application_departments', 'ended_at')
    op.drop_table('application_control_results')
    op.drop_table('department_controls')
    # ### end Alembic commands ###
