"""deleted scrap

Revision ID: 9b6ab3553704
Revises: 8a2a97e044a3
Create Date: 2026-02-02 22:03:23.850451

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "9b6ab3553704"
down_revision: Union[str, Sequence[str], None] = "8a2a97e044a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ---------- user_responses ----------
    op.drop_constraint(
        op.f("user_responses_ibfk_3"),
        "user_responses",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("user_responses_ibfk_1"),
        "user_responses",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("user_responses_ibfk_2"),
        "user_responses",
        type_="foreignkey",
    )

    op.drop_index(op.f("ix_user_responses_checklist_id"), table_name="user_responses")
    op.drop_index(op.f("ix_user_responses_control_id"), table_name="user_responses")
    op.drop_index(op.f("ix_user_responses_user_id"), table_name="user_responses")

    op.drop_table("user_responses")

    # # ---------- answers ----------
    op.drop_constraint(op.f("answers_ibfk_1"), "answers", type_="foreignkey")
    op.drop_constraint(op.f("answers_ibfk_2"), "answers", type_="foreignkey")
    op.drop_table("answers")

    # ---------- questions ----------
    op.drop_constraint(op.f("questions_ibfk_1"), "questions", type_="foreignkey")
    op.drop_table("questions")

    # ---------- sections ----------
    op.drop_constraint(op.f("sections_ibfk_1"), "sections", type_="foreignkey")
    op.drop_table("sections")

    # # ---------- controls ----------
    op.drop_constraint(op.f("controls_ibfk_1"), "controls", type_="foreignkey")
    op.drop_index(op.f("ix_controls_checklist_id"), table_name="controls")
    op.drop_table("controls")

    # # ---------- checklist_assignments ----------
    op.drop_constraint(
        op.f("checklist_assignments_ibfk_1"),
        "checklist_assignments",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("checklist_assignments_ibfk_2"),
        "checklist_assignments",
        type_="foreignkey",
    )
    op.drop_table("checklist_assignments")

    # # ---------- submissions ----------
    op.drop_constraint(op.f("submissions_ibfk_1"), "submissions", type_="foreignkey")
    op.drop_constraint(op.f("submissions_ibfk_2"), "submissions", type_="foreignkey")
    op.drop_constraint(op.f("submissions_ibfk_3"), "submissions", type_="foreignkey")
    op.drop_constraint(op.f("applications_ibfk_3"), "applications", type_="foreignkey")

    op.drop_table("submissions")

    # ---------- drafts & priorities ----------
    op.drop_table("pre_assessment_res_drafts")

    op.drop_constraint(
        op.f("user_priorities_ibfk_1"), "user_priorities", type_="foreignkey"
    )
    op.drop_index(op.f("ix_user_priority_unique"), table_name="user_priorities")
    op.drop_table("user_priorities")

    # ---------- pre_assessments ----------
    op.drop_table("pre_assessments")

    # ---------- checklists (NOW SAFE) ----------
    op.drop_constraint(op.f("checklists_ibfk_2"), "checklists", type_="foreignkey")
    op.drop_constraint(op.f("checklists_ibfk_3"), "checklists", type_="foreignkey")
    op.drop_table("checklists")

    # ---------- applications ----------
    op.drop_column("applications", "ticket_id")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applications", sa.Column("ticket_id", mysql.VARCHAR(length=40), nullable=True)
    )
    op.create_foreign_key(
        op.f("applications_ibfk_3"),
        "applications",
        "submissions",
        ["ticket_id"],
        ["id"],
    )
    op.create_table(
        "controls",
        sa.Column("checklist_id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("control_area", mysql.VARCHAR(length=100), nullable=False),
        sa.Column("severity", mysql.VARCHAR(length=50), nullable=False),
        sa.Column("control_text", mysql.MEDIUMTEXT(), nullable=False),
        sa.Column("id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.Column(
            "is_active",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("description", mysql.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["checklist_id"], ["checklists.id"], name="controls_ibfk_1"
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_controls_checklist_id"), "controls", ["checklist_id"], unique=False
    )
    op.create_table(
        "pre_assessments",
        sa.Column("assessment_type", mysql.VARCHAR(length=512), nullable=False),
        sa.Column("description", mysql.TEXT(), nullable=True),
        sa.Column("id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.Column(
            "is_active",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "user_responses",
        sa.Column("control_id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("user_id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("current_setting", mysql.MEDIUMTEXT(), nullable=True),
        sa.Column("review_comment", mysql.MEDIUMTEXT(), nullable=True),
        sa.Column("evidence_path", mysql.MEDIUMTEXT(), nullable=True),
        sa.Column("id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.Column(
            "is_active",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("checklist_id", mysql.VARCHAR(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["checklist_id"], ["checklists.id"], name=op.f("user_responses_ibfk_3")
        ),
        sa.ForeignKeyConstraint(
            ["control_id"], ["controls.id"], name=op.f("user_responses_ibfk_1")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("user_responses_ibfk_2")
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_user_responses_user_id"), "user_responses", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_responses_control_id"),
        "user_responses",
        ["control_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_responses_checklist_id"),
        "user_responses",
        ["checklist_id"],
        unique=False,
    )
    op.create_table(
        "submissions",
        sa.Column("user_id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("assessment_id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("status", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.Column(
            "is_active",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("assessed_by", mysql.VARCHAR(length=40), nullable=True),
        sa.ForeignKeyConstraint(
            ["assessed_by"], ["users.id"], name="submissions_ibfk_3"
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"], ["pre_assessments.id"], name="submissions_ibfk_2"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="submissions_ibfk_1"),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "checklist_assignments",
        sa.Column("checklist_id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("user_id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.Column(
            "is_active",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["checklist_id"],
            ["checklists.id"],
            name=op.f("checklist_assignments_ibfk_1"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("checklist_assignments_ibfk_2")
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "answers",
        sa.Column("submission_id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("question_id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("answer_text", mysql.TEXT(), nullable=True),
        sa.Column("id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.Column(
            "is_active",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["question_id"], ["questions.id"], name=op.f("answers_ibfk_2")
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"], ["submissions.id"], name=op.f("answers_ibfk_1")
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "sections",
        sa.Column("assessment_id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("title", mysql.VARCHAR(length=512), nullable=False),
        sa.Column("id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.Column(
            "is_active",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"], ["pre_assessments.id"], name="sections_ibfk_1"
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "questions",
        sa.Column("section_id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("question_text", mysql.TEXT(), nullable=False),
        sa.Column("id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.Column(
            "is_active",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["section_id"], ["sections.id"], name=op.f("questions_ibfk_1")
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "pre_assessment_res_drafts",
        sa.Column("user_id", mysql.VARCHAR(length=36), nullable=False),
        sa.Column("assessment_id", mysql.VARCHAR(length=36), nullable=False),
        sa.Column("responses", mysql.JSON(), nullable=True),
        sa.Column("id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.Column(
            "is_active",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["pre_assessments.id"],
            name=op.f("pre_assessment_res_drafts_ibfk_1"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("pre_assessment_res_drafts_ibfk_2")
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "user_priorities",
        sa.Column("user_id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("target_type", mysql.VARCHAR(length=20), nullable=False),
        sa.Column("target_id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column(
            "priority",
            mysql.INTEGER(),
            server_default=sa.text("'2'"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.Column(
            "is_active",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("user_priorities_ibfk_1")
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_user_priority_unique"),
        "user_priorities",
        ["user_id", "target_type", "target_id"],
        unique=True,
    )
    op.create_table(
        "checklists",
        sa.Column("app_id", mysql.VARCHAR(length=40), nullable=True),
        sa.Column("checklist_type", mysql.VARCHAR(length=512), nullable=False),
        sa.Column("creator_id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.Column(
            "is_active",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "is_completed",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("status", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("comment", mysql.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["app_id"],
            ["applications.id"],
            name=op.f("checklists_ibfk_3"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"], ["users.id"], name=op.f("checklists_ibfk_2")
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
