"""(add):scope to exec summary

Revision ID: a2830c855e39
Revises: 
Create Date: 2026-04-13 09:55:26.790475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2830c855e39'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executive_summaries', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('executive_summaries', sa.Column('scope', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'executive_summaries', 'departments', ['department_id'], ['id'], onupdate='cascade', ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'executive_summaries', type_='foreignkey')
    op.drop_column('executive_summaries', 'scope')
    op.drop_column('executive_summaries', 'department_id')
    # ### end Alembic commands ###
