"""adding default flag for dept questions

Revision ID: a9340d420e38
Revises: 635aab99b3c6
Create Date: 2026-02-03 17:36:47.266077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9340d420e38'
down_revision: Union[str, Sequence[str], None] = '635aab99b3c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_dept_questions', sa.Column('is_default', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_dept_questions', 'is_default')
    # ### end Alembic commands ###
