"""evidence changes

Revision ID: ab22b99ce4f6
Revises: 5a72d175b3e9
Create Date: 2026-01-02 11:33:58.448571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ab22b99ce4f6'
down_revision: Union[str, Sequence[str], None] = '5a72d175b3e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_evidences', sa.Column('comment_id', sa.String(length=40), nullable=False))
    op.create_foreign_key(None, 'application_evidences', 'comments', ['comment_id'], ['id'])
    op.drop_column('application_evidences', 'comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_evidences', sa.Column('comment', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'application_evidences', type_='foreignkey')
    op.drop_column('application_evidences', 'comment_id')
    # ### end Alembic commands ###
