"""link app and app question set

Revision ID: cabf34056c62
Revises: 334b4b84b3ca
Create Date: 2026-02-09 09:14:40.473100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cabf34056c62'
down_revision: Union[str, Sequence[str], None] = '334b4b84b3ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('question_set_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'applications', 'question_sets', ['question_set_id'], ['id'], ondelete='set null')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'question_set_id')
    # ### end Alembic commands ###
