"""app url made text


Revision ID: d0b7c7ce999f
Revises: 7f8a9e973543
Create Date: 2026-01-22 21:56:59.525941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd0b7c7ce999f'
down_revision: Union[str, Sequence[str], None] = '7f8a9e973543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'app_url',
               existing_type=mysql.VARCHAR(length=888),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'app_url',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=888),
               existing_nullable=True)
    # ### end Alembic commands ###
