"""(add): added description to each option

Revision ID: d1d67269e04b
Revises: d4b5cdc33b35
Create Date: 2026-03-09 19:07:21.388622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd1d67269e04b'
down_revision: Union[str, Sequence[str], None] = 'd4b5cdc33b35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_question_options', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('application_question_options', 'text',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=212),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_question_options', 'text',
               existing_type=sa.String(length=212),
               type_=mysql.TEXT(),
               existing_nullable=False)
    op.drop_column('application_question_options', 'description')
    # ### end Alembic commands ###
