"""(change): option selection questionnaire for app

Revision ID: d4b5cdc33b35
Revises: 9944d7d9acee
Create Date: 2026-03-09 18:56:50.263833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd4b5cdc33b35'
down_revision: Union[str, Sequence[str], None] = '9944d7d9acee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_answers', 'answer_option_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'application_answers', 'application_question_options', ['answer_option_id'], ['id'], onupdate='cascade', ondelete='set null')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application_answers', type_='foreignkey')
    op.alter_column('application_answers', 'answer_option_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
