"""(fix): addedd category to the app questions

Revision ID: f309e05b12f5
Revises: d1d67269e04b
Create Date: 2026-03-11 16:16:04.248907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f309e05b12f5'
down_revision: Union[str, Sequence[str], None] = 'd1d67269e04b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_questions', sa.Column('category', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_questions', 'category')
    # ### end Alembic commands ###
