"""(add_on):user, data types to app

Revision ID: f83353200cc3
Revises: 
Create Date: 2026-01-29 09:51:19.273636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f83353200cc3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('user_type', sa.String(length=252), nullable=True))
    op.add_column('applications', sa.Column('data_type', sa.String(length=252), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'data_type')
    op.drop_column('applications', 'user_type')
    # ### end Alembic commands ###
