"""tracking dept wise started date and request raised date

Revision ID: fad375d21a43
Revises: 43f47a031841
Create Date: 2026-03-03 09:15:35.995989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fad375d21a43'
down_revision: Union[str, Sequence[str], None] = '43f47a031841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_departments', sa.Column('started_at', sa.Date(), nullable=True))
    op.add_column('applications', sa.Column('requested_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'requested_date')
    op.drop_column('application_departments', 'started_at')
    # ### end Alembic commands ###
